steps:
    -name:'gcr.io/cloud-builders/docker'
     args: ['build', '-t', 'gcr.io/tam-energy-consumption/healthcare_chatbot', '.']
    -name:'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/tam-energy-consumption/healthcare_chatbot']
