#version: '3'
services:
  chat_api:
    build:
      context: ./chat_api
    env_file:
      - .env
    #networks:
     #- healthcare_chatbot_default
    ports:
      - "8000:8000"
    

  chatbot_frontend:
    build:
      context: ./chatbot_frontend
    env_file:
      - .env
    #networks:
     #- healthcare_chatbot_default
    depends_on:
      - chat_api
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - "8501:8501"
    
  